### PR TITLE
feat: Add input validation and word processing

### PR DESCRIPTION
**Pull request by SHABIN-K**
- Trim leading/trailing spaces and remove empty lines from word list
- Validate words to ensure they contain only letters and have at least 2 characters

### CODE REVIEW

**Comment by anandbaburajan** [comment]
Thanks a lot @SHABIN-K! I've also made some changes in the mobile part, and yep, the mobile code is a bit messy :D

**Comment by SHABIN-K** [comment]
Thanks for the update, @anandbaburajan! I was thinking—how about replacing the textarea with a multi-selection input? It could make things more user-friendly!

 like this 
image

**Comment by anandbaburajan** [comment]
That's a nice idea, @SHABIN-K. Do you know which is the best tag input component available? I'm aware of these two: https://emblor.jaleelbennett.com/introduction & https://github.com/react-tags/react-tags.

**Comment by SHABIN-K** [comment]
> That's a nice idea, @SHABIN-K. Do you know which is the best tag input component available? I'm aware of these two: https://emblor.jaleelbennett.com/introduction & https://github.com/react-tags/react-tags.

Both of those look good, but I prefer the first one. Let’s give it a try!

**Comment by anandbaburajan** [comment]
Cool, do you want to take this up? And, curious to know how you found out about Wordamour and why you decided to contribute. And, have you created one already for your partner? :D

**Comment by SHABIN-K** [comment]
> Cool, do you want to take this up? And, curious to know how you found out about Wordamour and why you decided to contribute. And, have you created one already for your partner? :D

Sure, I’d love to take this up! I found Wordamour while exploring open-source projects and thought it was cool.Haven’t made one for my partner yet—**but I did create a custom chat system for her since she’s in the hostel! It's been a fun way to stay connected!** 😄

**Pull request merged**
