### PR TITLE
Refactor: Replaced textarea with TagInput component for improved word list management

### PR DESCRIPTION
**Pull request by SHABIN-K**

### CODE REVIEW

**Comment by anandbaburajan** [comment]
Thanks @SHABIN-K!

Some comments:

- The words box needs to have a fixed height with a scroll (it currently grows too long and hides the other inputs)
- Let's remove the `wordsList.length >= 32` condition since the component handles that itself
- `words.length === 0 || words.length < 2` can be just `words.length < 2`
- Let's allow words with spaces like "Ex Machina" and it should just show up as "EXMACHINA" in the grid
- On a closer look, there's an unnecessary shadow for the component
- Let's remove the "0/32" message since when the max limit is reached, the component already shows "Max tags reached"
- On a related note, let's rename the message to "Maximum words reached"

Unrelated: let's only exclude numbers and the common special characters (such as !, @, #, etc). There could be people using letter such as ñ, Ç, ß, á, é, í, ó, ú, etc., in different languages.

**Comment by anandbaburajan** [comment]
@SHABIN-K hey, still working on this?

**Comment by SHABIN-K** [comment]
> @SHABIN-K hey, still working on this?

Sorry, I can’t work on this right now due to time constraints. Thanks for understanding!

**Comment by anandbaburajan** [comment]
Cool, no worries, you can open a new PR with the feedback later. Thanks!

**Pull request closed without merging**
